---
title: "Glossary"
format: html
---

Many of these concepts are contested or take different meanings in different contexts. These are working definitions rooted in the readings as a starting point. 

**Anti-politics:** Ways of removing questions from political debate. An "argument stopper" (Purdy, p. 21) to "naturalize," one version of politics while excluding others from serious debate. Ways of evading politics, shutting down imagination and mobilization (e.g., by claiming that certain questions have been decided by nature) (Purdy, p. 31). 

**Politics:** Ways of having and resolving debates over what to do together. 

**Democracy:** A form of politics that strives for equal *voice* in debates and decision-making processes, and where a *vote* of all citizens plays decisive role in decisions about what to do (Purdy, p. 49-50). In addition to equality of votes and voice, Purdy also includes an exemplary/prophetic dimension of democracy related to the ability of citizens to live in different ways (including protections for diversity in speech in religion that are often called **liberal democracy**) and thus sever as a model for future policy and politics. 

**Ideology** (also called world views, ways of seeing, styles of environmental imagination): Sets of assumptions and values that structure decisions. We may be more aware of some of these assumptions and values than others, i.e., some may be explicit and some may be implicit. 




