---
title: "Reading for Anthropocene"
format: html
---


Adaptation 

- [Preparing our cities for the climate crisis. Geophysicist Klaus Jacob on how we can adapt our cities to live with rising seas and heavier rains.](https://kpfa.org/episode/behind-the-news-october-14-2021/)

Agriculture

- [Report: Increased Accountability, Sustainability Needed in Farm Credit System ](https://www.sfntoday.com/2024/01/08/report-increased-accountability-sustainability-needed-in-farm-credit-system/)

Degrowth

- [Is “degrowth” the answer to the climate crisis? Economists Peter Victor and Robert Pollin debate the virtues of “degrowth” in avoiding climate catastrophe.](https://kpfa.org/episode/behind-the-news-november-4-2021/)

- [Matt Huber criticizes the climate austerity camp.](https://newleftreview.org/sidecar/posts/mish-mash-ecologism) and and talks about it on [Behind the News](https://kpfa.org/episode/behind-the-news-august-25-2022/).

COP 26

[What happened (or didn’t) at the COP26 climate summit, and what Bannon wants to do to the bureaucracy.](https://kpfa.org/episode/behind-the-news-november-18-2021/) Environmental journalist Tina Gerhardt reviews the accomplishments, or lack thereof, at the COP26 climate summit in Glasgo. And renegade ex-Republican Mike Lofgren (author of this article) explains why Steve Bannon’s dream of deconstructing the administrative state is really bad.
