---
title: "PubPol 475.011 Topics: Climate Change: Politics for the Anthropocene"
subtitle: "Winter 2024"
format: 
 html:
   toc: true
   toc-location: left
execute:
  echo: false
---

Tuesdays and Thursdays 2:30-3:50 AM, 1210 Weill Hall

Instructor: Devin Judge-Lord, <judgelor@umich.edu>, 715-204-4287

Office hours: Tuesday and Thursday 10-11 AM, 3215 Weill Hall

<!--Updated `r Sys.Date() |> format("%B %d, %Y")` https://github.com/judgelord/PP510/commits/main/docs/syllabus-PP510-fall-2023.html)--> 


> [“We live in a big science fiction novel we are all writing together” - Kim Stanley Robinson](https://www.nytimes.com/2022/05/11/books/kim-stanley-robinson-sci-fi.html)


	
# Course Objectives

In the past century---the blink of an eye in ecological time---a small portion of humans concentrated in wealthier and more industrialized countries began to radically transform the ecology of our planet at an unprecedented scale.^[OK, sure, cyanobacteria were [similarly tranfromative](https://asm.org/articles/2022/february/the-great-oxidation-event-how-cyanobacteria-change), but that was billions of years ago, and cyanobacteria cannot reflect on their actions. They make oxygen, but neither politics nor policy.] 

This class aims to help you develop your own critique of various policy fights over what to do about our new relationship with our biosphere. 

Experts increasingly see the slow policy response to climate science as having less to do with climate science and more to do with politics. That is, climate change is increasingly seen as a problem for the social sciences to address. Thus, this class is about politics. "Politics" can mean many things, and a core objective of this class is understanding different forms of politics---different ways of having and resolving debates about who our community is and what we will do together about the challenges we face. Climate policy debates reflect well-established political and economic perspectives but also raise new, unique issues. 

The core readings are mostly drawn from political science, political theory, and law. They are accompanied by op-eds and podcasts from advocates and journalists covering climate policy debates. Both the theories of politics and political arguments cover a wide range of perspectives. We will read a range of critiques based on visions of good politics---from left to right, religious to utilitarian, populist to technocratic---with the aim of recognizing and critiquing these forms of politics when we see them in the wild. 

The assignments for this class are motivated by the observation that politics is fundamentally an organized activity. Thus, the critiques we develop in this class will target organizations. It is easy to critique those with whom we severely disagree, but they are the least likely to listen to you. Thus, the critiques you develop in this class will be aimed at the organizations you see as having the best chance of making a positive difference in the world---specifically, the organizations for whom you hope to work. You may have no idea what your future career looks like; that is fine. Perhaps you will find an organization or cause that inspires you in this class. Or perhaps you have a very clear idea of your future career. In that case, this class will challenge you to think about how organizations in your intended field of work engage in politics and policy---and how they might do so differently. It is not a requirement that the organizations you address are activist organizations. Indeed, activist organizations may be the most difficult to critique because they already have a well-developed approach to politics and policy. You may even see yourself working for an organization strongly opposed to most proposed climate policies; that is fine. For example, if you aim to work at Exxon-Mobil, you might look to Business School scholarship to formulate a critique like [this one](https://ssir.org/articles/entry/time_to_put_the_fossil_fuel_industry_into_hospice). 

As practice for developing your skills in both effective writing and constructive criticism, peer critiques of your colleagues' writing are a major part of this class and 15% of your grade.


# Course Readings/Other Materials

Each week's required readings are indented and marked with a grey sidebar. I also often note "resources" or "further readings" with bullets---these are not required readings.

I call on students during class and expect you to do all assigned readings for each week before Tuesday’s class (discussion posts are due Monday evening). 

##	Required Books

We will read large portions of three books: 

- *After Nature* by Jedediah Purdy, Harvard University Press (2015)

- *All We can Save*, Edited by Anyana Elizabeth Johnson & Katharine K. Wilkinson (2021) --- available as an audio book from the library!

- *Charleston: Race, Water, and the Coming Storm* by Susan Crawford (2023)

The other readings will be available for free online (you may need to go through the library website for journal articles) or on Canvas.

##	Recommended Books

We will read smaller portions of the following books, which will be available on Canvas: 

- [Deva Woodly. 2015. The Politics of Common Sense: How Social Movements Use Public Discourse to Change Politics and Win Acceptance, Oxford University Press.](https://global.oup.com/academic/product/the-politics-of-common-sense-9780190203986?cc=us&lang=en&)
- *Politics: The Central Texts* by Roberto Mangabeira Unger
- [*The Big Fix: Seven Practical Steps to Save Our Planet* by Hal Harvey and Justin Gillis](https://www.simonandschuster.com/books/The-Big-Fix/Hal-Harvey/9781982123994)
- [Gazmararian, Alexander F., and Dustin Tingley. Uncertain Futures: How to Unlock the Climate Impasse. Cambridge University Press](www.uncertainfuturesbook.com)
- Oreskes, N., & Conway, E. M. (2011). Merchants of doubt: How a handful of scientists obscured the truth on issues from tobacco smoke to global warming. Bloomsbury Publishing


## Other books you may find useful

- *Politics is for Power* by Eitan Hersh
- *Governing the Commons: The evolution of institutions for collective action. Cambridge University Press.* by Elinor Ostrom. Available electronically through the library!
- *Rules for Radicals* by Saul Alinsky
- *Policy Paradox:  The Art of Political Decision Making* by Deborah Stone
  - Scans of the following chapters from an older edition: [1](https://www.cide.edu/wp-content/uploads/2020/10/Stone-Deborah-POLICY-PARADOX.pdf), [all](https://ebooks.aiu.ac.ke/show/975/pdf)

## Resources 

### American Government Module

If you are looking for more foundation in how government works, the Ford School organized an Intro to American Government Module taught by Political Science Ph.D. candidate Ciera Hammond: 

- [Day 1](http://leccap.engin.umich.edu/leccap/player/r/jdCaYX)
- [Day 2](http://leccap.engin.umich.edu/leccap/player/r/r4jN5e)
- [Day 3](http://leccap.engin.umich.edu/leccap/player/r/bSYi7Y)
- [Day 4](http://leccap.engin.umich.edu/leccap/player/r/fANcTy)

# Learning environment

Learning from each other is only possible if we show the respect due to our fellow citizens of this class.

To realize this goal, I expect us to respect our colleagues and cultivate inclusive discussions. This means that we must be careful not to mislead, degrade, interrupt someone who does not speak as much, or enforce hierarchies based on race, religion, ethnicity, nationality, gender expression, sexual orientation, or ability.

<!--[Best Practices for Navigating the Classroom Environment - 
Fall 2022](https://docs.google.com/document/d/1uSAbeIoEHqZwBzBlbDsz_jl5J_mapwoRxyOK1OGhBdM)--> 

## Ford School and University of Michigan Policies

**Ford School Inclusivity Statement:**
Members of the Ford School community represent a rich variety of backgrounds and perspectives. We are committed to providing an atmosphere for learning that respects diversity. While working together to build this community, we ask all members to: 

- share their unique experiences, values, and beliefs
- be open to the views of others
- honor the uniqueness of their colleagues
- appreciate the opportunity that we have to learn from each other in this community
- value one another’s opinions and communicate in a respectful manner
- keep confidential discussions that the community has of a personal (or professional) nature
- use this opportunity together to discuss ways in which we can create an inclusive environment in Ford - classes and across the UM community


Being a constructive member of a diverse community is always a learning process. The University has many resources to help us in this endeavor, including a [glossary of terms]( 
https://www.dropbox.com/sh/7whjk69ckv3h39r/AAAsKb3tOl4OulF63-mJsHa1a/Glossary%20of%20Terms?dl=0&preview=Clearinghouse+-+Glossary.pdf&subfolder_nav_tracking=1).

**Ford School Public Health Protection Policy.**  In order to participate in any in-person aspects of this course---including meeting with other students to study or work on a team project---you must follow all the public health safety measures and policies put in place by the State of Michigan, Washtenaw County, the University of Michigan, and the Ford School. Up-to-date information on U-M policies can be found on the  [U-M Health Response website](https://campusblueprint.umich.edu/).  It is expected that you will protect and enhance the health of everyone in the Ford School community by staying home and following self-isolation guidelines if you are experiencing any symptoms of COVID-19. 

**Student Mental Health and Wellbeing.**  The University of Michigan is committed to advancing the mental health and wellbeing of its students.  We acknowledge that a variety of issues, both those relating to the pandemic and other issues such as strained relationships, increased anxiety, alcohol/drug problems, and depression, can directly impact students’ academic performance and overall wellbeing. If you or someone you know is feeling overwhelmed, depressed, and/or in need of support, services are available. 

You may access the Ford School’s embedded counselor Paige Ziegler (pziegler@umich.edu) and/or counselors and urgent services at [Counseling and Psychological Services (CAPS)](https://caps.umich.edu/) and/or [University Health Service (UHS)](https://www.uhs.umich.edu/mentalhealthsvcs).  Students may also use the Crisis Text Line (text '4UMICH' to 741741) to be connected to a trained crisis volunteer.  You can find additional resources both on and off campus through the [University Health Service](https://uhs.umich.edu/stressresources) and through [CAPS](https://caps.umich.edu/article/um-mental-health-resources).

**Student/Faculty Interaction Best Practices.** We strive to ensure a safe learning environment free from gender-based and sexual harassment, sexual violence, retaliation, and a hostile environment based on discrimination and intimidation. We make the following commitments:  

- To conduct office hours with the door open unless the student requests a closed-door meeting;
- To document meeting times with students so that this record can be reviewed;
- To meet students individually only at university venues;
- To conduct off-campus meetings only at places where alcohol is not served;
- To communicate electronically with students only on university platforms and not on social media, text, or non-university apps.
- For more information on resources for reporting sexual misconduct, please see [the faculty senate best practices for faculty interactions](https://facultysenate.umich.edu/wp-content/uploads/2022/08/BEST-PRACTICES-FOR-FACULTY-_-STUDENT-INTERACTIONS.pdf) and [U-M's page on Sexual and Gender-Based Misconduct](https://sexualmisconduct.umich.edu/).


**Accommodations for Students with Disabilities:**  
Accommodations for Students with Disabilities: The University of Michigan recognizes disability as an integral part of diversity and is committed to creating an inclusive and equitable educational environment for students with disabilities. Students who are experiencing a disability-related barrier should visit the Services for Students with Disabilities website. They can be reached at 734-763-3000 or ssdoffice@umich.edu. For students who are connected with SSD, accommodation requests can be made in Accommodate. If you have any questions or concerns, please contact your SSD Coordinator or visit SSD’s Current Student webpage. SSD considers aspects of the course design, course learning objects, and the individual academic and course barriers experienced by the student. Further conversation with SSD, instructors, and the student may be warranted to ensure an accessible course experience.

::: {.callout-important}
**If you require accommodations from SSD, please start that process quickly because it takes time. **
:::

**Academic Integrity:**  The Ford School academic community, like all communities, functions best when its members treat one another with honesty, fairness, respect, and trust. We hold all members of our community to high standards of scholarship and integrity. To accomplish its mission of providing an optimal educational environment and developing leaders of society, the Ford School promotes the assumption of personal responsibility and integrity and prohibits all forms of academic dishonesty, plagiarism, and misconduct. Academic dishonesty may be understood as any action or attempted action that may result in creating an unfair academic advantage for oneself or an unfair academic advantage or disadvantage for any other member or members of the academic community. Plagiarism involves representing the words, ideas, or work of others as one’s own in writing or presentations, and failing to give full and proper credit to the original source. Conduct, without regard to motive, that violates academic integrity and ethical standards will result in serious consequences and disciplinary action. The Ford School's policy of academic integrity can be found in the [MPP](https://www.dropbox.com/s/wuq2jfmbpflm4f2/FINAL%202023%20Masters%20Handbook.pdf?dl=0),  [BA](https://www.dropbox.com/s/zhllbd4vpfr439r/FINAL%202023%20BA%20Handbook.pdf?dl=0), and [Ph.D. Program](https://www.dropbox.com/s/06x1tzt1e32pjjw/FINAL%202023%20PHD%20Handbook.pdf?dl=0) handbooks. Additional information regarding academic dishonesty, plagiarism, and misconduct and their consequences is available at [U-M's academic-policies page]( http://www.rackham.umich.edu/current-students/policies/academic-policies/section11#112).



**Use of Technology:**  Students should follow instructions from their instructor as to acceptable use of technology in the classroom, including laptops, in each course. All course materials (including slides, assignments, handouts, pre-recorded lectures, or recordings of class) are to be considered confidential material and are not to be shared in full or part with anyone outside of the course participants. Likewise, your own personal recording (audio or video) of your classes or office hour sessions is allowed only with the express written permission of your instructor.  If you wish to post course materials or photographs/videos of classmates or your instructor to third-party sites (e.g., social media), you must first have informed consent. Without explicit permission from the instructor and, in some cases, your classmates, the public distribution or posting of any photos, audio/video recordings, or pre-recordings from class, discussion section, or office hours, even if you have permission to record, is not allowed and could be considered academic misconduct.

Please review additional information and policies regarding [academic expectations and resources](https://intranet.fordschool.umich.edu/academic-expectations) at the Ford School of Public Policy.

See the end of the syllabus for information about our commitment to best practices of instructor/student interactions. 

## Generative Text Tools Using [SALAMI](https://blog.quintarelli.it/2019/11/lets-forget-the-term-ai-lets-call-them-systematic-approaches-to-learning-algorithms-and-machine-inferences-salami/) 

You learn by doing work, and I assess your learning by the work you do. You may use tools to help craft your writing, but you must learn the crafts of constructive critique and persuasive writing to succeed in class. To add value to any employer or cause, you must craft arguments and recommendations that are significantly better than they would get by asking a generative text tool. I expect the same. 

Text extruded by LLMs is, by construction, derivative of patterns of words already linked together on the internet. In some sense, everything we do is derivative of our experiences, but the generative process is very different for thinking subjects than for a language model. Language models are incapable of producing original critiques. If they produce something that sounds insightful, it is only because we are able to assign meaning to the strings of words they extrude. (It also probably sounds right because resembles things already written by a human on the internet.) Language models have no sense of meaning and cannot judge the consistency, coherence, or logic of an argument.  I expect the critiques you produce to be yours and for you to stand by them as intellectual projects. No LLM can help you justify your thought process and reasoning to me. LLMs have no thought process and do no reason. 

I am not yet sure if LLMs are a helpful tool for the craft of persuasive writing or learning this craft. I worry that they may constrain creativity by focusing our attention on problems and solutions that already exist and have already been frequently linked in the source material on which the LLMs are trained. Additionally, in many fields, including political science, rich White men are disproportionately the authors of the source texts. Uncritically using LLMs trained on biased source material risks reinforcing biases.

Good policy and political strategy rests on good evidence. Many LLMs fabricate evidence. Work submitted with <mark>fake sources or made-up facts will get a 0</mark> for similar reasons that other forms of academic dishonesty make your work worse than worthless. The key recommendation of experts studying how students can effectively use LLMs is to craft a solid bibliography first and constrain generative tools to those sources. You will still have to do significant work to make sure that sources are used and cited appropriately, but this is much easier than finding real evidence to replace fake evidence and *then* making sure it is used and cited correctly. 

Thus, <mark>**references must be hyperlinked**</mark> whenever possible; I will be checking to make sure sources of evidence are used appropriately. 

If you use people or tools other than your brain and spelling/grammar checkers to string words together, you should be prepared to comment on what you used it for, what it got right, and what it got wrong. 

I reserve the right to discuss your papers in length with you if I have concerns.

# Assignments 

Credit hours will be earned by attending two classes of $1.3\bar{3}$ hours each, reading and preparing written work outside of class for 6 to 9 hours per week, and a series of assignments building to a highly-polished op-ed style critique of an organization's approach to climate policy. A key part of the process will be critiquing the writing of others.

> <mark>**Discussion posts are due Mondays at 7 PM.** </mark>

> <mark>**All other assignments and critiques are due every Tuesday at 7 PM.** </mark>

::: {.callout-important}
There is an assignment due **every** Tuesday. 
:::

> <mark>**All assignments are to be submitted on Canvas.** </mark>


[Subscribe to the due dates calendar]().

## Find your voice - 10% of final grade

- Week 1: a 20-30 second video introducing yourself to the class (1%)
- Week 2: list the 20 top organizations for whom you would like to work (1%)^[Most organizations have an email list---I suggest signing up, both for the assignments in this class and your future career.] 
- Week 3: 10 op-ed-style headlines (in-class peer workshop on headlines) (1%) <!---COULD BE 1--> 
- Week 4: 5 revised headlines + first 200 words - no longer than 2 pages + annotated bibliography (5%)
- Week 5: 
  - Meet with me about your op-ed ideas (part of previous assignment grade)
  - Write to a public official or agency. Post 100-200 words about it and a link to the opportunity on Canvas. (1%) For example, you might [Comment on a proposed federal agency policy](https://www.regulations.gov/), [Comment on a proposed state agency policy](https://ars.apps.lara.state.mi.us/) (sort by Filing Date to see Pending rules), Recommend a course of action to one of [your elected representatives](https://www.usa.gov/elected-officials) )  
- At some point during the first half of the semester, pitch one of your critiques to the class. Two students will pitch their ideas each week. This will give you practice testing out your argument and presentation skills (1%)

## Craft your critique - 25% of final grade

- Week 6: 3 first 400 words + annotated bibliographies  (9%)
- Week 7: peer critique of first 400 words  (5%)
- Week 8: 2 revised first 400 words + annotated bibliographies  (10%)
- Week 9: my feedback on your first 400 words 
  - Write 100-200 words about why it is important to engage in a particular policy process and link to the opportunity on Canvas OR Write no more than 240 characters (plus a link to the opportunity) on why people should engage that is shared by at least five other people on a public forum---post a link or screenshots to Canvas (1%)

## Hone your critique - 50% of final grade

Through multiple rounds of revision, you will hone your critique, improving your logic and writing (writing can always be improved).

::: {.callout-important}
I am mostly grading on how you respond to feedback. If you would like, you can include revision comments (200 words max) on the document in Canvas addressing any points where you feel context is needed for me to understand how you incorporated feedback.
:::

- Week 10: 750-800 word op-ed + annotated bibliography  (10%)
- Week 11: peer critique of op-ed  (5%)
- Week 12: revised op-ed (10%)
- Week 13: my feedback on op-ed 
- Week 14: revised op-ed (10%)
- Week 15: peer critique of revised op-ed  (5%)
- Week 16: final due (10%)

## Participation 15% (15 X 1%) 

#### Participation posts to Canvas are <mark>due by 7 p.m. every Monday</mark>

In addition to attending class, we will continue the conversation by discussing readings and assignment tasks on Canvas. 

# Readings 

## Week 1: Hope 

...in an unequal and chaotic world.

> [*Home is Always Worth It* - Mary Annaïse Heglar](https://medium.com/@maryheglar/home-is-always-worth-it-d2821634dcd9)

> [*But the Greatest of These is Love* - Mary Annaïse Heglar](https://medium.com/@maryheglar/but-the-greatest-of-these-is-love-4b7aad06e18c)

> [Temple, James. 2021. “The rare spots of good news on climate change”](https://www.technologyreview.com/2021/12/23/1042973/climate-change-action-progress-clean-energy/)

## Week 2: Politics

...in the Anthropocene

> Purdy, Prologue and Introduction (1-50)

Further Readings: 

- [“Introduction: Paths to Witnessing, Ethics of Speaking Out”, Nancy Lipton Rosenblum, *Daedalus* (2020)](https://www.amacad.org/publication/introduction-paths-witnessing-ethics-speaking-out)
- [Global warming will happen faster than we think, Y Xu, V Ramanathan, DG Victor, *Nature* (2018)](https://www.nature.com/articles/d41586-018-07586-5)


## Week 3: God and Nature

The religious, colonial, and mystic foundations of Western environmental law and politics

> Purdy, Chapter 1: An Unequal Terrain (51-70), Chapter 2: God's Avid Gardeners (70-95) and Chapter 4: Natural Utopias (116-152)

The black church as a site of modern climate advocacy 

> All We Can Save: Greens Are Just as Good as Kale by Heather McTeer Toney

<!--## Nature as Teacher

Aesthetics--> 

## Week 4: Justice 

> “Three faces of climate justice”, *Annual Review of Political Science (2022) by Nives Dolšak and Aseem Prakash. Vol. 25:283-301

>  ["Race, Class, Gender, and American Environmentalism. US Forest Service General Technical Report PNW-GTR-534" (2002) by Dorceta Taylor](https://doi.org/10.2737/PNW-GTR-534) <!--could also go under movements--> (1-41)

Further reading: 

> *Roosevelt Project Gulf Coast case* (2022) by Jason Beckfield et al.  1-30, https://ceepr.mit.edu/wp-content/uploads/2022/12/2022-The-Roosevelt-Project-Gulf-Coast-Case-Study.pdf


## Week 5: Utilitarianism and Techno-optimism 

Utilitarianism and managerialism: 

> Purdy, Chapter 5: A Conservationist Empire (153-187)

Learning curves: 

> [*The Big Fix: Seven Practical Steps to Save Our Planet* by Hal Harvey and Justin Gillis](https://www.simonandschuster.com/books/The-Big-Fix/Hal-Harvey/9781982123994), Chapter 1: The Learning Curve (1-35)

Climate engineering: 

> *All We Can Save: A Handful of Dust* by Kate Marvel 

Further Reading: 

- Chapter 5, *Ethics and Politics* in *A Case for Climate Engineering* by David Keith
- [*Under a White Sky: The Nature of the Future* by Elizabeth Kolbert](https://www.penguinrandomhouse.com/books/617060/under-a-white-sky-by-elizabeth-kolbert/)


## Week 6: Ecological Critique

> *A Sand County Almanac* by Aldo Leopold (201-226)

> Purdy, Chapter 6: A Wilderness Passage into Ecology (188-227), Chapter 7: Environmental Law in the Anthropocene (228-255), and Chapter 8: What Kind of Democracy (256-288)

## Indigenous Critique 

> [Andrea Tunks, “Tangata Whenua Ethics and Climate Change”](https://heinonline.org/HOL/Page?handle=hein.journals/nzjel1&id=73&collection=journals&index=)

> [Indigenous Environmental Justice, Renewable Energy Transition, and the Infrastructure of Sovereignty](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003214380-13/indigenous-environmental-justice-renewable-energy-transition-infrastructure-sovereignty-kyle-whyte)

::: {.callout-caution collapse="true"}
TBD Selections from *All We Can Save* and others
:::


Further reading:

-[Whyte, K., Bruscato, N., David-Chavez, D., Dockry, M., Johnson, M., Jones, C., and Leonard, K. 2023. Chapter 16, Tribes and Indigenous Peoples. U.S. 5th National Climate Assessment.](https://nca2023.globalchange.gov/chapter/16/)

## Planning for Change

> [*Charleston: Race, Water, and the Coming Storm* by Susan Crawford (Select Chapters TBD)](http://pegasusbooks.com/books/charleston-9781639363575-hardcover)

> Listen: [Volts: Minnesota forces transportation planners to take climate change seriously](https://www.volts.wtf/p/minnesota-forces-transportation-planners#details)


Further Reading: 

- [3 cities face a climate dilemma: to build or not to build homes in risky places](https://www.npr.org/2023/11/06/1204923950/arizona-california-new-jersey-climate-flood-wildfire-drought-building-homes)
- [Climate Change Will Force a New American Migration - Abrahm Lustgarten, ProPublica](https://www.propublica.org/article/climate-change-will-force-a-new-american-migration)


## Institutions 

Collective action 

- Ostrom, E. (2010). Beyond markets and states: polycentric governance of complex economic systems. *American economic review*, 100(3), 641-72.


Electoral institutions

> Skim: ["Legislative Staff and Representation in Congress" by Hertel-Fernandez, Alexander; Mildenberger, Matto; Stokes, Leah C. *The American Political Science Review*](https://www.cambridge.org/core/journals/american-political-science-review/article/legislative-staff-and-representation-in-congress/D7735FCF39B843B9F3269FD39362FD66)

> Skim [“Institutions, Climate Change, and the Foundations of Long-term Policymaking.” Finnegan, Jared, 2022 *Comparative Political Studies*.
]()


Further reading

- Ostrom, E. (1990). Governing the commons: The evolution of institutions for collective action. Cambridge University Press.  


## Markets

Voices of New Keynesian, neoliberal, and libertarian economists: 

- ["Information" - Joseph E. Stiglitz
](https://www.econlib.org/library/Enc/Information.html)
- ["The Use of Knowledge in Society"
By Friedrich A. Hayek](https://www.econlib.org/library/Essays/hykKnw.html?chapter_num=1#book-reader)
- [Gotham’s Airheaded Carbon Law](https://www.city-journal.org/article/gothams-airheaded-carbon-law)

Research: 

> Listen: [Paying for Pollution](https://scholars.org/podcast/paying-pollution)

Criticism: 

> [Thinking like an Economist: How Efficiency Replaced Equality in U.S. Public Policy (Selections TBD)](https://press.princeton.edu/books/hardcover/9780691167381/thinking-like-an-economist)
> [Excerpts from “The Big Myth: How American Business Taught Us to Loathe Government and Love the Free Market”](https://news.harvard.edu/gazette/story/2023/03/excerpt-from-naomi-oreskes-the-big-myth/)

Criticism of the critics: 

- [The War on Economics by Idrees Kahloon (Washington bureau chief for The Economist )](https://www.newyorker.com/magazine/2022/05/23/the-war-on-economics-elizabeth-popp-berman-thinking-like-an-economist)


## Movements 

- To what extent have climate movements been effective, and why?
- To what extent are the underlying features of the climate politics outlined by McAdam in 2017 still true? 

> [Chapter 1. Deva Woodly. 2015. The Politics of Common Sense: How Social Movements Use Public Discourse to Change Politics and Win Acceptance, Oxford University Press.](https://global.oup.com/academic/product/the-politics-of-common-sense-9780190203986?cc=us&lang=en&)

> McAdam, Doug. 2017. “Social Movement Theory and the Prospects for Climate Change Activism in the United States.” *Annual Review of Political Science* 20:189–2008.

> “Three faces of climate justice”, Annual Review of Political Science, 2022, by Nives Dolšak and Aseem Prakash. Vol. 25:283-301

## Incumbents

Explaining action and inaction 

- Why are groups effective at shaping policy? 
- What industries will lose from climate policies, and could they pivot?
<!--- Identify examples of “odd bed-fellows”--> 
- What industries have most effectively obstructed policy? How do they work with/against political actors?

The global political economy of climate policy:

> Colgan, Jeff D., Jessica F. Green, and Thomas N. Hale. 2020. “Asset Revaluation and the Existential Politics of Climate Change.” *International Organization*

US political economy of climate policy: 

> [Carbon Captured: How Business and Labor Control Climate Politics, Chapter 2: The Logic of Double Representation by Matto Mildenberger](https://direct.mit.edu/books/book/4620/chapter/211959/The-Logic-of-Double-Representation)

> [Short Circuiting Policy: Interest Groups and the Battle Over Clean Energy and Climate Policy in the American States, Chapter 3 An Institutional History of Electricity Politics and Climate Inaction](https://academic.oup.com/book/32159/chapter/268128410)

<!--
> Watch: [Leah Stokes - The Future is Electric | Bioneers 2023](https://www.youtube.com/watch?v=57Ry9LnUW0g)
--> 


> Catie's article on utility lobbying? 

Further Reading: 

- [Op-Ed: Yes, ExxonMobil misled the public by NAOMI ORESKES AND GEOFFREY SUPRAN](https://www.latimes.com/opinion/op-ed/la-oe-oreskes-supran-exxonmobil-20170901-story.html)
- [Winners and Losers of Energy and Climate Policy – How Can the Costs Be Redistributed?](https://www.cesifo.org/en/publikationen/2021/journal-complete-issue/cesifo-forum-052021-winners-and-losers-energy-and-climate)


## Doomerism and Delay

Tuesday: Doomerism

Light doomerism: 

> Watch [Weekend Update: U.N.'s Climate Change Report - SNL](https://www.youtube.com/watch?v=07oe1m67eik)

Heavy doomerism: 

> 

Thursday: Reactionary Rhetoric 

Research: 

> ["Does climate denialism still matter? The prevalence of alternative frames in opposition to climate policy" by Heather W. Cann and Leigh Raymond](https://www.tandfonline.com/doi/full/10.1080/09644016.2018.1439353)

> Oreskes, N., & Conway, E. M. (2011). Merchants of doubt: How a handful of scientists obscured the truth on issues from tobacco smoke to global warming. Bloomsbury Publishing USA. Chapter 6.

Further Reading: 

- https://www.latimes.com/opinion/op-ed/la-oe-oreskes-supran-exxonmobil-20170901-story.html

- Brookings Institute, Elaine Kamarck, The Challenging Politics of Climate Change 


<!--## Utopia


Further Reading

- Review of new books on Utopian thinking: https://link.springer.com/article/10.1057/s41296-023-00661-1#citeas

--> 

## US Climate Policy 

> All We Can Save: Litigating in a Time of Crisis (51-59), The Politics of Policy (85-91)

::: {.callout-caution collapse="true"}
> TBD 

:::

Further reading: 

Cap-and-trade: 

- [Naming the Problem: What It Will Take to Counter Extremism and Engage Americans in the Fight against Global Warming by Theda Skocpol](https://grist.org/wp-content/uploads/2013/03/skocpol-captrade-report-january-2013y.pdf)
- [What Theda Skocpol gets right about the cap-and-trade fight by David Roberts](https://grist.org/climate-energy/what-theda-skocpol-gets-right-about-the-cap-and-trade-fight/)


Resources for understanding the Inflation Reduction Act: 

 - [Our Green Transition May Leave Black People Behind](https://hammerandhope.org/article/climate-green-new-deal)

- ["Inflation Reduction Act (IRA) Summary: Energy and Climate Provisions" - Bipartisan Policy Center ](https://bipartisanpolicy.org/blog/inflation-reduction-act-summary-energy-climate-provisions/)
 - [Breaking Down the Inflation Reduction Act. Program by Program. Incentive by Incentive. A sortable and filterable list for stakeholders big and small.](https://rmi.org/breaking-down-the-inflation-reduction-act-program-by-program-incentive-by-incentive/)
- [Investments trackers](https://jackconness.com/ira-chips-investments)
- [Report detailing IRA's impact on US emissions + economy and public health](https://energyinnovation.org/publication/updated-inflation-reduction-act-modeling-using-the-energy-policy-simulator/)
- ["Emissions and energy impacts of the Inflation Reduction Act" *Science*](https://science.org/doi/10.1126/science.adg3781)
- https://www.charged-the-book.com/na-ev-supply-chain-map

Criticism: 

> [Climate Bidenomics by Alyssa Battistoni and Geoff Mann](https://newleftreview.org/issues/ii143/articles/alyssa-battistoni-geoff-mann-climate-bidenomics)


## Feminist Critique 

Eco-feminist Critique: 

> ["Alive in the Sunshine" by Alyssa Battistoni ](https://jacobin.com/2014/01/alive-in-the-sunshine)

## Nationalist Critique

<!--Military experts warn us our national security is threatened by massive waves of climate refugees destabilizing countries around the world. - Al Gore--> 

Great power competition, neo-Malthusian, and ethno-nationalist critique: 

> [Climate-Trap Diplomacy](https://www.city-journal.org/article/china-is-no-climate-partner)

> [The Tragedy of the Commons by Garrett Hardin ](The Tragedy of the Commons)

> [*U.S. Immigration Environment* from the Federation for American Immigration Reform](https://www.fairus.org/sites/default/files/2017-08/FAIR_2016_Environmental_Report.pdf)


::: {.callout-warning}
The Southern Poverty Law Center designates [FAIR as a Hate Group](https://www.splcenter.org/fighting-hate/extremist-files/group/federation-american-immigration-reform) and [Hardin as an Extreamist White Nationalist](https://www.splcenter.org/fighting-hate/extremist-files/individual/garrett-hardin). While all assigned readings have a perspective, these views most starkly contrast the University of Michigan's stated goals and policies. And yet, these views are increasingly prominent in climate policy discourse, so it is important to understand them.
:::

Critique of the neo-Malthusian and ethno-nationalist critique: 

> [The Tragedy of the Tragedy of the Commons by Matto Mildernberger](https://blogs.scientificamerican.com/voices/the-tragedy-of-the-tragedy-of-the-commons/)

> [The Malthusians Are Back: Climate activists who worry that the world has too many people are joining an ugly tradition.](https://www.theatlantic.com/ideas/archive/2023/03/population-control-movement-climate-malthusian-similarities/673450/)

> [Climate denial is waning on the right. What’s replacing it might be just as scary](https://www.theguardian.com/environment/2021/nov/21/climate-denial-far-right-immigration)

> [*How fascism works.* By Sean Illing interview with Jason Stanley for Vox](https://www.vox.com/2018/9/19/17847110/how-fascism-works-donald-trump-jason-stanley)

Further critique of neo-Malthusian ideas: 

[Neo‐Malthusianism and Coercive Population Control in China and India: Overpopulation Concerns Often Result in Coercion](https://www.cato.org/policy-analysis/neo-malthusianism-coercive-population-control-china-india-overpopulation-concerns#history-neo-malthusianism) (Climate change is only discussed in the Introduction, the rest is not so relevant)


Further Research: 

- [Information about climate-induced migration spurs negative attitudes about immigrants by  Kaitlin Raimi](https://fordschool.umich.edu/news/2023/information-about-climate-induced-migration-spurs-negative-attitudes-about-immigrants)
- [‘Ecobordering’: casting immigration control as environmental protection by Joe Turner and Dan Bailey](https://www.tandfonline.com/doi/full/10.1080/09644016.2021.1916197)
- [The origins of totalitarianism by Hannah Arendt](https://search.lib.umich.edu/catalog/record/99187311787206381?query=Origins+of+Totalitarianism&utm_source=lib-home)



## Examining Our Assumptions

Critics of Marxism and Liberalism: 

> *Politics: The Central Texts* by Roberto Mangabeira Unger: Introduction (V-XVI) and Chapter 1 (1-18)

## Ammendments 

Because many topics we cover are subjects of ongoing discussion, I may make occasional changes to the course readings over the semester. I will notify you of any substantive changes. The full revision history is [on github](https://github.com/judgelord/PP510/commits/main/docs/syllabus-PP510-fall-2023.html).

<!-- MORE IDEAS 

https://www.climateandcommunity.org/

[A Planet to Win: Why We Need a Green New Deal by Kate Aronoff, Alyssa Battistoni, Daniel Aldana Cohen, and Thea Riofrancos](https://www.versobooks.com/products/2546-a-planet-to-win)


Climate Crisis and the Global Green New Deal: The Political Economy of Saving the Planet
by Noam Chomsky and Robert Pollin

Climate Leviathan: A Political Theory of Our Planetary Future
by Geoff Mann and Joel Wainwright


The Conservation Revolution: Radical Ideas for Saving Nature Beyond the Anthropocene
by Bram Büscher and Robert Fletcher


Climate Change as Class War: Building Socialism on a Warming Planet
by Matthew T. Huber

Who Will Build the Ark?: Debates on Climate Strategy from 'New Left Review'
Edited by Benjamin Kunkel and Lola Seaton


- https://www.nytimes.com/interactive/2021/10/25/climate/world-climate-pledges-co26.html
- [Countries’ climate pledges built on flawed data (2021)](https://www.washingtonpost.com/climate-environment/interactive/2021/greenhouse-gas-emissions-pledges-data/)
- [Climate Pledges COP26 (2021)](https://www.nytimes.com/interactive/2021/10/25/climate/world-climate-pledges-co26.html)
- [Why tackling global warming is a challenge without precedent](https://www.economist.com/schools-brief/2020/04/23/why-tackling-global-warming-is-a-challenge-without-precedent)
---> 




---

<!--exclude: true-->

## More Information on Student Instructor Best Practices

We will conduct office hours with my door open unless you request otherwise.

Students who wish to have confidential conversations with me may schedule a private meeting via Zoom or may ask to have a closed-door meeting. But this closed-door meeting must be made on your request in writing, even on the spot. I will never suggest a closed-door meeting myself because of the power dynamic.

We will document all pre-scheduled meetings between the instructor and the student via Google Calendar (or other software) and/or university email.

Students who email to request an office hour appointment should expect to receive an email confirmation or a Google Calendar (or other software) invitation from me, or, upon my email confirmation and request, may send me a Google Calendar (or other software) invitation for this meeting. The purpose is to provide a permanent record of the meeting and to ensure that all class activities are documented and transparent. Students who choose to drop by for informal meetings are welcome to do so, but there will be no documentation provided. (See above for open-door policy.)

We will choose meeting locations and conduct meetings with student and instructor safety in mind.

We will ensure that all individual meetings between instructor/student will take place at university venues.

We will ensure that all off-campus meetings, trips, or events must engage with course material.

Off-campus meetings will not involve alcohol or take place at locations that serve alcohol. If the class goes out for a meal, it will be at a cafe or restaurant that does not serve alcohol. The location/day/time of any off-campus meetings between the instructor and students will be documented in Google Calendar (or other software).

We, the instructors, will conduct all individual communications using the University platforms of email, Canvas, Slack, or Piazza, with the caveat that we may use non-university platforms set up by students (such as GroupMe) only if they include all students in the class.

There will be no instructor-student private communications on any non-University platforms, such as social media, GroupMe, WhatsApp, etc.

For more information on resources for reporting sexual misconduct, please see [the faculty senate best practices for faculty interactions](https://facultysenate.umich.edu/wp-content/uploads/2022/08/BEST-PRACTICES-FOR-FACULTY-_-STUDENT-INTERACTIONS.pdf) and [U-M's page on Sexual and Gender-Based Misconduct](https://sexualmisconduct.umich.edu/).
